refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d} - {m}{n}"
  requests:
    kind: file
    path: "log/requests.log"
    encoder:
      pattern: "{m}{n}"
root:
  level: info
  appenders:
    - stdout
loggers:
  app::backend::db:
    level: info
  app::requests:
    level: info
    appenders:
      - requests
    additive: false
